### ISSUE TITLE
GNET now ranks first. check the techempower benchmark again, pls update README.md

### ISSUE THREAD

**Issue by sprappcom** [cristaloleg/awesome-go-perf#18]
[gnet](https://github.com/panjf2000/gnet) - high-performance, lightweight, non-blocking, event-driven networking framework written in pure Go. Ranks #10 in TechEmpower Plaintext Benchmark, beating all other go frameworks.

**Comment by cristaloleg** [comment]
See https://github.com/go-perf/awesome-go-perf#network

**Comment by sprappcom** [comment]
@cristaloleg check this again
https://www.techempower.com/benchmarks/#hw=ph&test=plaintext&section=data-r22

it's now first! #1 golang net framework faster than rust / c++ / c

so it's good to let everyone know. and also mention it as Round 22 then you wont need to update the readme again.

**Comment by cristaloleg** [comment]
I don't see a good reason to follow TechEmpower rating. Too much updates for no reason. Thanks 😉
